import { chromium } from 'playwright';
const browser = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport:{width:1280,height:720} });
page.on('pageerror',e=>console.log('[PAGEERROR]',e.message));
await page.goto('http://localhost:8099/index.html');
await page.waitForFunction(()=>document.getElementById('loader')?.classList.contains('hidden'),{timeout:180000});
await page.click('#btn-start'); await page.waitForTimeout(300);
await page.click('#btn-quick'); await page.waitForTimeout(300);
await page.click('#btn-battle'); await page.waitForTimeout(2000);
await page.evaluate(()=>{ window.TW.spawn(7,3); window.TW.allies(3,2); });
await page.waitForTimeout(1500);
console.log(await page.evaluate(()=>{
  const b=window.__app.battle, dt=1/60, N=500;
  const time=(fn)=>{ const t0=performance.now(); for(let i=0;i<N;i++) fn(); return +((performance.now()-t0)/N).toFixed(3); };
  b.keys.KeyW=true;
  const res={};
  res.total = time(()=>b.update(dt));
  res.player = time(()=>b.updatePlayer(dt));
  res.ai = time(()=>{ for(const e of b.enemies) b._updateUnit(e,dt); for(const a of b.allies) b._updateUnit(a,dt); });
  res.projectiles = time(()=>b.updateProjectiles(dt));
  res.fx = time(()=>b.fx.update(dt));
  res.camera = time(()=>b.updateCamera(dt));
  res.hud = time(()=>b.updateHUD(dt));
  res.minimap = time(()=>b.drawMinimap());
  res.damageFx = time(()=>{ for(const e of b.enemies) b.emitDamageFx(e.tank,dt); });
  res.losChecks = time(()=>{ for(const e of b.enemies) b.field.blocked(e.pos, b.player.pos); });
  res.suspension = time(()=>{ for(const e of b.enemies) e.tank.updateSuspension(dt); });
  b.keys.KeyW=false;
  res.particlesLive = b.fx.smoke.count+b.fx.hot.count+b.fx.spark.count+b.fx.dust.count;
  res.units = b.enemies.length + b.allies.length;
  return res;
}));
await browser.close();
